### ISSUE TITLE
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-carburants-flux-instantane-v2 does not exist.'}

### ISSUE THREAD

**Issue by lboue** [Aohzan/hass-prixcarburant#46] opened 2024-04-18 12:02 UTC
**Describe the bug**
The requested dataset prix-carburants-flux-instantane-v2 does not exist:

```
2024-04-18 14:00:19.825 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Prix Carburant for prix_carburant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/__init__.py", line 58, in async_setup_entry
    await tool.init_stations_from_location(
  File "/config/custom_components/prix_carburant/tools.py", line 145, in init_stations_from_location
    response_count = await self._request_api(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/tools.py", line 89, in _request_api
    raise PrixCarburantToolRequestError(
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-carburants-flux-instantane-v2 does not exist.'}
2024-04-18 14:00:23.474 DEBUG (MainThread) [custom_components.prix_carburant.tools] Load stations names from local file stations_name.json
2024-04-18 14:00:23.628 INFO (MainThread) [custom_components.prix_carburant] Init stations list near Home-Assistant location
2024-04-18 14:00:23.629 DEBUG (MainThread) [custom_components.prix_carburant.tools] Call https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/prix-carburants-flux-instantane-v2/records API to retrieve station data
2024-04-18 14:00:23.751 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Prix Carburant for prix_carburant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/__init__.py", line 58, in async_setup_entry
    await tool.init_stations_from_location(
  File "/config/custom_components/prix_carburant/tools.py", line 145, in init_stations_from_location
    response_count = await self._request_api(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/tools.py", line 89, in _request_api
    raise PrixCarburantToolRequestError(
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-carburants-flux-instantane-v2 does not exist.'}
```

**Configuration**
From UI or in configuration.yaml (paste it here between ```xxx```)

**Expected behavior**

**Screenshots**

**Debug logs**
![image](https://github.com/Aohzan/ipx800v5/assets/2736322/4e2a69a3-db12-4c6d-9aa5-a96aa2e4a2e1)
```
Paste debug logs here
```

**Comment by Aohzan** [comment] 2024-04-18 12:03
duplicate of https://github.com/Aohzan/hass-prixcarburant/issues/45

**Closed by Aohzan** 2024-04-18 12:03 UTC
Labels: bug
